controller_list:
  - name: both_arms_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
  - name: left_hand_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - victor_left_gripper_fingerA_joint_2
      - victor_left_gripper_fingerA_joint_3
      - victor_left_gripper_fingerA_joint_4
      - victor_left_gripper_fingerB_joint_2
      - victor_left_gripper_fingerB_joint_3
      - victor_left_gripper_fingerB_joint_4
      - victor_left_gripper_fingerB_knuckle
      - victor_left_gripper_fingerC_joint_2
      - victor_left_gripper_fingerC_joint_3
      - victor_left_gripper_fingerC_joint_4
      - victor_left_gripper_fingerC_knuckle
  - name: right_hand_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - victor_right_gripper_fingerA_joint_2
      - victor_right_gripper_fingerA_joint_3
      - victor_right_gripper_fingerA_joint_4
      - victor_right_gripper_fingerB_joint_2
      - victor_right_gripper_fingerB_joint_3
      - victor_right_gripper_fingerB_joint_4
      - victor_right_gripper_fingerB_knuckle
      - victor_right_gripper_fingerC_joint_2
      - victor_right_gripper_fingerC_joint_3
      - victor_right_gripper_fingerC_joint_4
      - victor_right_gripper_fingerC_knuckle
