# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: right_arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - victor_left_arm_joint_1
    - victor_left_arm_joint_2
    - victor_left_arm_joint_3
    - victor_left_arm_joint_4
    - victor_left_arm_joint_5
    - victor_left_arm_joint_6
    - victor_left_arm_joint_7
    - victor_left_gripper_fingerA_joint_2
    - victor_left_gripper_fingerA_joint_3
    - victor_left_gripper_fingerA_joint_4
    - victor_left_gripper_fingerB_knuckle
    - victor_left_gripper_fingerB_joint_2
    - victor_left_gripper_fingerB_joint_3
    - victor_left_gripper_fingerB_joint_4
    - victor_left_gripper_fingerC_knuckle
    - victor_left_gripper_fingerC_joint_2
    - victor_left_gripper_fingerC_joint_3
    - victor_left_gripper_fingerC_joint_4
    - victor_right_arm_joint_1
    - victor_right_arm_joint_2
    - victor_right_arm_joint_3
    - victor_right_arm_joint_4
    - victor_right_arm_joint_5
    - victor_right_arm_joint_6
    - victor_right_arm_joint_7
    - victor_right_gripper_fingerA_joint_2
    - victor_right_gripper_fingerA_joint_3
    - victor_right_gripper_fingerA_joint_4
    - victor_right_gripper_fingerB_knuckle
    - victor_right_gripper_fingerB_joint_2
    - victor_right_gripper_fingerB_joint_3
    - victor_right_gripper_fingerB_joint_4
    - victor_right_gripper_fingerC_knuckle
    - victor_right_gripper_fingerC_joint_2
    - victor_right_gripper_fingerC_joint_3
    - victor_right_gripper_fingerC_joint_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_left_arm_joint_1
    - victor_left_arm_joint_2
    - victor_left_arm_joint_3
    - victor_left_arm_joint_4
    - victor_left_arm_joint_5
    - victor_left_arm_joint_6
    - victor_left_arm_joint_7
  gains:
    victor_left_arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_arm_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_arm_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_right_gripper_fingerA_joint_2
    - victor_right_gripper_fingerA_joint_3
    - victor_right_gripper_fingerA_joint_4
    - victor_right_gripper_fingerB_knuckle
    - victor_right_gripper_fingerB_joint_2
    - victor_right_gripper_fingerB_joint_3
    - victor_right_gripper_fingerB_joint_4
    - victor_right_gripper_fingerC_knuckle
    - victor_right_gripper_fingerC_joint_2
    - victor_right_gripper_fingerC_joint_3
    - victor_right_gripper_fingerC_joint_4
  gains:
    victor_right_gripper_fingerA_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerA_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerA_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerB_knuckle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerB_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerB_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerB_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerC_knuckle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerC_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerC_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_gripper_fingerC_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_left_gripper_fingerA_joint_2
    - victor_left_gripper_fingerA_joint_3
    - victor_left_gripper_fingerA_joint_4
    - victor_left_gripper_fingerB_knuckle
    - victor_left_gripper_fingerB_joint_2
    - victor_left_gripper_fingerB_joint_3
    - victor_left_gripper_fingerB_joint_4
    - victor_left_gripper_fingerC_knuckle
    - victor_left_gripper_fingerC_joint_2
    - victor_left_gripper_fingerC_joint_3
    - victor_left_gripper_fingerC_joint_4
  gains:
    victor_left_gripper_fingerA_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerA_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerA_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerB_knuckle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerB_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerB_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerB_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerC_knuckle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerC_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerC_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_left_gripper_fingerC_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_right_arm_joint_1
    - victor_right_arm_joint_2
    - victor_right_arm_joint_3
    - victor_right_arm_joint_4
    - victor_right_arm_joint_5
    - victor_right_arm_joint_6
    - victor_right_arm_joint_7
  gains:
    victor_right_arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_arm_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    victor_right_arm_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1