move_group:
  # MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
  # Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.1
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
      - victor_left_gripper_fingerA_joint_2
      - victor_left_gripper_fingerA_joint_3
      - victor_left_gripper_fingerA_joint_4
      - victor_left_gripper_fingerB_knuckle
      - victor_left_gripper_fingerB_joint_2
      - victor_left_gripper_fingerB_joint_3
      - victor_left_gripper_fingerB_joint_4
      - victor_left_gripper_fingerC_knuckle
      - victor_left_gripper_fingerC_joint_2
      - victor_left_gripper_fingerC_joint_3
      - victor_left_gripper_fingerC_joint_4
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
      - victor_right_gripper_fingerA_joint_2
      - victor_right_gripper_fingerA_joint_3
      - victor_right_gripper_fingerA_joint_4
      - victor_right_gripper_fingerB_knuckle
      - victor_right_gripper_fingerB_joint_2
      - victor_right_gripper_fingerB_joint_3
      - victor_right_gripper_fingerB_joint_4
      - victor_right_gripper_fingerC_knuckle
      - victor_right_gripper_fingerC_joint_2
      - victor_right_gripper_fingerC_joint_3
      - victor_right_gripper_fingerC_joint_4
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: right_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - victor_right_arm_joint_1
        - victor_right_arm_joint_2
        - victor_right_arm_joint_3
        - victor_right_arm_joint_4
        - victor_right_arm_joint_5
        - victor_right_arm_joint_6
        - victor_right_arm_joint_7
    - name: right_gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - victor_right_gripper_fingerA_joint_2
        - victor_right_gripper_fingerA_joint_3
        - victor_right_gripper_fingerA_joint_4
        - victor_right_gripper_fingerB_knuckle
        - victor_right_gripper_fingerB_joint_2
        - victor_right_gripper_fingerB_joint_3
        - victor_right_gripper_fingerB_joint_4
        - victor_right_gripper_fingerC_knuckle
        - victor_right_gripper_fingerC_joint_2
        - victor_right_gripper_fingerC_joint_3
        - victor_right_gripper_fingerC_joint_4
    - name: left_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - victor_left_arm_joint_1
        - victor_left_arm_joint_2
        - victor_left_arm_joint_3
        - victor_left_arm_joint_4
        - victor_left_arm_joint_5
        - victor_left_arm_joint_6
        - victor_left_arm_joint_7
    - name: left_gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - victor_left_gripper_fingerA_joint_2
        - victor_left_gripper_fingerA_joint_3
        - victor_left_gripper_fingerA_joint_4
        - victor_left_gripper_fingerB_knuckle
        - victor_left_gripper_fingerB_joint_2
        - victor_left_gripper_fingerB_joint_3
        - victor_left_gripper_fingerB_joint_4
        - victor_left_gripper_fingerC_knuckle
        - victor_left_gripper_fingerC_joint_2
        - victor_left_gripper_fingerC_joint_3
        - victor_left_gripper_fingerC_joint_4
# Left arm
#==================================
victor_left_arm_joint_1_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_1
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

victor_left_arm_joint_2_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_2
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

victor_left_arm_joint_3_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_3
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

victor_left_arm_joint_4_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_4
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

victor_left_arm_joint_5_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_5
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

victor_left_arm_joint_6_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_6
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

victor_left_arm_joint_7_controller:
  type: position_controllers/JointPositionController
  joint: victor_left_arm_joint_7
  pid: {p: 1000, i: 10.1, d: 100.0, i_clamp_max: 100.0, i_clamp_min: -100.0}

left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_left_arm_joint_1
    - victor_left_arm_joint_2
    - victor_left_arm_joint_3
    - victor_left_arm_joint_4
    - victor_left_arm_joint_5
    - victor_left_arm_joint_6
    - victor_left_arm_joint_7
  gains:
    victor_left_arm_joint_1: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_arm_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_arm_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_arm_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_arm_joint_5: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_arm_joint_6: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_arm_joint_7: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    victor_left_arm_joint_1: {trajectory: 0.1, goal: 0.1}
    victor_left_arm_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_left_arm_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_left_arm_joint_4: {trajectory: 0.1, goal: 0.1}
    victor_left_arm_joint_5: {trajectory: 0.1, goal: 0.1}
    victor_left_arm_joint_6: {trajectory: 0.1, goal: 0.1}
    victor_left_arm_joint_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_right_arm_joint_1
    - victor_right_arm_joint_2
    - victor_right_arm_joint_3
    - victor_right_arm_joint_4
    - victor_right_arm_joint_5
    - victor_right_arm_joint_6
    - victor_right_arm_joint_7
  gains:
    victor_right_arm_joint_1: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_arm_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_arm_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_arm_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_arm_joint_5: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_arm_joint_6: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_arm_joint_7: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    victor_right_arm_joint_1: {trajectory: 0.1, goal: 0.1}
    victor_right_arm_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_right_arm_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_right_arm_joint_4: {trajectory: 0.1, goal: 0.1}
    victor_right_arm_joint_5: {trajectory: 0.1, goal: 0.1}
    victor_right_arm_joint_6: {trajectory: 0.1, goal: 0.1}
    victor_right_arm_joint_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

right_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_right_gripper_fingerA_joint_2
    - victor_right_gripper_fingerA_joint_3
    - victor_right_gripper_fingerA_joint_4
    - victor_right_gripper_fingerB_knuckle
    - victor_right_gripper_fingerB_joint_2
    - victor_right_gripper_fingerB_joint_3
    - victor_right_gripper_fingerB_joint_4
    - victor_right_gripper_fingerC_knuckle
    - victor_right_gripper_fingerC_joint_2
    - victor_right_gripper_fingerC_joint_3
    - victor_right_gripper_fingerC_joint_4
  gains:
    victor_right_gripper_fingerA_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerA_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerA_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerB_knuckle: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerB_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerB_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerB_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerC_knuckle: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerC_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerC_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_right_gripper_fingerC_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    victor_right_gripper_fingerA_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerA_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerA_joint_4: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerB_knuckle: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerB_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerB_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerB_joint_4: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerC_knuckle: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerC_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerC_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_right_gripper_fingerC_joint_4: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

left_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - victor_left_gripper_fingerA_joint_2
    - victor_left_gripper_fingerA_joint_3
    - victor_left_gripper_fingerA_joint_4
    - victor_left_gripper_fingerB_knuckle
    - victor_left_gripper_fingerB_joint_2
    - victor_left_gripper_fingerB_joint_3
    - victor_left_gripper_fingerB_joint_4
    - victor_left_gripper_fingerC_knuckle
    - victor_left_gripper_fingerC_joint_2
    - victor_left_gripper_fingerC_joint_3
    - victor_left_gripper_fingerC_joint_4
  gains:
    victor_left_gripper_fingerA_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerA_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerA_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerB_knuckle: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerB_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerB_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerB_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerC_knuckle: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerC_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerC_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    victor_left_gripper_fingerC_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    victor_left_gripper_fingerA_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerA_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerA_joint_4: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerB_knuckle: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerB_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerB_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerB_joint_4: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerC_knuckle: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerC_joint_2: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerC_joint_3: {trajectory: 0.1, goal: 0.1}
    victor_left_gripper_fingerC_joint_4: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10
